image: Visual Studio 2015

environment:
  nodejs_version: "10"

platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version
  - npm i

test_script:
  - npm run test

build: off

branches:
  only:
    - master
